### ISSUE TITLE
Check "ID" field is incorrect and fails validation with Consul 1.7

### ISSUE THREAD

**Issue by ncouse** [vert-x3/vertx-consul-client#74]
In Consul 1.7 they have introduced strict validation of JSON payloads. 

Any requests containing invalid payload will return a 400 error. Previously, the invalid field would have been ignored.

Consul 1.7 came out this week, automated tests against the latest Docker image started failing. The issue is related to this validation.

I narrowed it down to registering a service using a Check.

```
ServiceOptions serviceOptions = new ServiceOptions()....
CheckOptions checkOptions = new CheckOptions().....

serviceOptions.setCheckOptions(checkOptions);
client.registerService(serviceOptions, result -> {...});
```

This fails consistently with Consul 1.7 whenever the `CheckOptions` are set, no matter what options I use.

Looking into it further, it looks like the code in `ConsulClientImpl.checkOpts`:

```
    JsonObject json = new JsonObject()
      .put("ID", checkOptions.getId())
```
`ID` is not valid, and it should be `CheckID`, if you consult with sample payload here: https://www.consul.io/api/catalog.html#sample-payload

I was testing this with 3.7.0, but code is still invalid on master.

I quickly recompiled with the change above (Change `ID` to `CheckID`), and my tests are now passing with Consul 1.7, so this appears to be a valid fix.

According to https://www.consul.io/api/catalog.html#check, the ID can be omitted and the name will be used as the ID. I guess this is what happened previously, as the wrong attribute was being used to set the CheckID field.

**Comment by ncouse** [comment]
Consul note on stricter JSON decoding: https://www.consul.io/docs/upgrade-specific.html#stricter-json-decoding

**Comment by ruslansennov** [comment]
@ncouse Thanks for the report. Could you check the current master version

**Comment by ncouse** [comment]
I have not tested on master version, but the code is still using the incorrect field name in master, so will fail in a similar manner.

**Comment by ruslansennov** [comment]
Field `ID` is still used in `/agent/check/register` endpoint (see https://www.consul.io/api/agent/check.html#register-check)

**Comment by ncouse** [comment]
This bug concerns the case where the check is part of the registration of your service.

The links in description above show this must be `CheckID`. It is probably inconsistent on Consul’s API, but it will fail now in Consul 1.7.

**Comment by ruslansennov** [comment]
> This bug concerns the case where the check is part of the registration of your service.

This bug has been fixed. Also, all tests passed with the consul 1.7.0 (which is released).

**Comment by ncouse** [comment]
I just tested with 3.8.5 (the latest release), and the bug is still there. I notice at least in 3.8.x that the error messages are better (than 3.7.0).

**Comment by ncouse** [comment]
I see there is an update on master (presumably for 4.x): https://github.com/vert-x3/vertx-consul-client/blob/master/src/main/java/io/vertx/ext/consul/impl/ConsulClientImpl.java#L450

I just tests with `4.0.0-milestone4` and get the same error.

**Comment by ruslansennov** [comment]
Fixes will be available in `3.8.6`, `3.9.0` etc

**Comment by ruslansennov** [comment]
You can try `3.8.6-SNAPSHOT` version

**Comment by ncouse** [comment]
Yes, I managed to find your snapshots repo, and testing 4.0.0-SNAPSHOT, and 3.8.6-SNAPSHOT. and both work for my use case.

Thanks.
